dwarf: fix exception on reg compare
match_optional_bool_cast() uses state.target_reg as one of the
parameters to reg_cmp.
However, this is optional parameter and may be None, which causes
exception as below:

DEBUG:__main__:[Match][handle_operand:1481]    |Handling int const '255' for reg None at a00002343c4
WARNING:__main__:Got exception 'NoneType' object has no attribute 'startswith'. Skipping that expr.
DEBUG:__main__:[HandleCU][process_cu:643]      |Traceback (most recent call last):
  File "/mcdc/xen/xen/../../mcdc-tool/mcdc_tool_dwarf.py", line 638, in process_cu
    ret.append(match_bool_expr(cu, elffile, next_expr.expr, instructions, inlines))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mcdc/xen/xen/../../mcdc-tool/mcdc_tool_dwarf.py", line 2043, in match_bool_expr
    recurse(expr, MatchState(0, partial=True))
  File "/mcdc/xen/xen/../../mcdc-tool/mcdc_tool_dwarf.py", line 1118, in result
    return func(arg1, state.derive(instr_idx=offset, target_reg=state.target_reg))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mcdc/xen/xen/../../mcdc-tool/mcdc_tool_dwarf.py", line 2023, in recurse
    return handle_eq_xor(e, state)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mcdc/xen/xen/../../mcdc-tool/mcdc_tool_dwarf.py", line 1939, in handle_eq_xor
    new_state = match_optional_bool_cast(new_state)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mcdc/xen/xen/../../mcdc-tool/mcdc_tool_dwarf.py", line 1136, in match_optional_bool_cast
    if instr.mnemonic in ("and", "bic") and reg_cmp(get_instr_reg_operand(instr, 1),
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mcdc/xen/xen/../../mcdc-tool/mcdc_tool_dwarf.py", line 1096, in reg_cmp
    if r2.startswith("x") or r2.startswith("w"):
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'

Signed-off-by: Ruslan Ruslichenko <Ruslan_Ruslichenko@epam.com>